# Numpy Day1

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
!pip install numpy

In [8]:
import numpy as np

In [13]:
list1=[2,3,4,5,6]
arr=np.array(list1)
print(type(list1))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.random.rand(5)

array([0.50623639, 0.67155904, 0.11181797, 0.59092093, 0.61253676])

In [37]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
arr2.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [36]:
arr3=np.array([
    [[1,2,3],[4,5,6]]
    ,[[7,8,9],[10,11,12]]])
print(arr3)
arr3.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


3

In [42]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [43]:
np.full((2,3,3),5)

array([[[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]])

In [46]:
np.random.randint(low=0,high=10,size=(2,3))

array([[1, 9, 7],
       [1, 7, 8]])

In [49]:
np.random.rand(3,3,3)

array([[[0.2368489 , 0.16970074, 0.2555701 ],
        [0.72908385, 0.68526942, 0.72858205],
        [0.60825266, 0.64932944, 0.76247637]],

       [[0.18291769, 0.89966287, 0.29719788],
        [0.72381652, 0.42045982, 0.9178068 ],
        [0.85342334, 0.6835466 , 0.53975551]],

       [[0.50804839, 0.33871637, 0.94092942],
        [0.78402887, 0.1941937 , 0.42641678],
        [0.58526929, 0.75440891, 0.78651938]]])

In [51]:
arr4=np.array([2.,4,5])
arr4

array([2., 4., 5.])

In [56]:
print(arr4,arr4.dtype)

[2. 4. 5.] float64


In [57]:
arr4,arr4.dtype

(array([2., 4., 5.]), dtype('float64'))

In [60]:
arr3.dtype,arr4.dtype

(dtype('int32'), dtype('float64'))

In [66]:
arr5=np.array([1,2,3,4,5],dtype='int64')
print(arr5.dtype)
arr6=arr5.astype('int32')
print(arr6.dtype)

int64
int32


In [72]:
arr2.ndim

2

In [73]:
arr3.shape

(2, 2, 3)

In [75]:
arr5.shape

(5,)

In [81]:
arr2.itemsize ,arr4.itemsize

(4, 8)

In [82]:
arr.data

In [83]:
arr2.data

In [84]:
arr3.data

In [96]:
np.savetxt('File.npy',arr2)
loaded=np.load('File.npy')
loaded

ValueError: Cannot load file containing pickled data when allow_pickle=False